### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#102]
On the header add link with name Admin panel before profile. Show that link only of the role of the user is admin in the local storage!

On route /admin-panel implement page, which contains few tabs. The tabs have to be:

- manage users
- manage homes
- manage lands

On manage users list all users and make buttons - edit and delete.
Same for homes and lands.

**Comment by alivadjid** [comment]
Assign to me, please

**Comment by alivadjid** [comment]
How can I access with role admin?

**Comment by DamyanBG** [comment]
Think, if you cant implement everything, write whatever your can and i will finish it
