### ISSUE TITLE
Combine user profile pages

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#103]
There are few pages, where a user can change his info - /profile, /change-password, /change-email. Combine them in one route /profile and separate them via tabs.

**Comment by c00kie123** [comment]
Hey, I can try working on this.

**Comment by DamyanBG** [comment]
Welcome to the project!

**Comment by DamyanBG** [comment]
@c00kie123 any progress?

**Comment by c00kie123** [comment]
I will try working on it this week. Can I ask where is the file to be changed located at?

**Comment by DamyanBG** [comment]
Open App.js and you can see the files related to the paths.

**Comment by c00kie123** [comment]
Hey, what do you think of this? I have added in the Tabs components as per your request
```
import React from 'react';
import {Tabs, Tab} from 'react-tabs';

function ProfilePage() {
    return (
        <Tabs>
            <Tab label="Profile">
                <Profile />
            </Tab>
            <Tab label="Change Email">
                <ChangeEmail />
            </Tab>
            <Tab label="Change Password">
                <ChangePassword />
            </Tab>
        </Tabs>
    )
}


function App() {
  return (
    <Routes>
      <Route path="/profile" element={<ProfilePage />} />
    </Routes>
  );
}
```

**Comment by c00kie123** [comment]
Do you need to edit the CSS as well? Other than CSS , is that it?

**Comment by c00kie123** [comment]
Do you need to edit the CSS also? Otherwise, is that all?

**Comment by DamyanBG** [comment]
I can't imagine the view just by code, I am still not that good :)

**Comment by c00kie123** [comment]
Haha! I guess I will try it in my environment first

**Comment by DamyanBG** [comment]
Hey, when you expect to have a chance to make a PR?
