### ISSUE TITLE
Remove urls.js

### ISSUE THREAD

**Issue by alivadjid** [DamyanBG/real-estate-react-app#106]
Propose to remove urls.js and store all links in .env
Also add .env.example for example

**Comment by DamyanBG** [comment]
I agree on half. I want to keep url.js. Just hostUrl = process.env.REACT_APP_URL for example. So we will keep using Adapter pattern.

**Comment by alivadjid** [comment]
okay, understand.  What about this? And remove console

**Comment by DamyanBG** [comment]
It is good.
