### ISSUE TITLE
All lands in Admin page

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#116]
List all lands in Manage lands tab in Admin page. The back end route is /lands. Add on every land button edit and delete.

**Comment by oderinde300** [comment]
Hi, am interested in solving this issue. How do I go about it and get assigned to it?

**Comment by DamyanBG** [comment]
Fixed by @alivadjid.

@oderinde300 you can choose other issue. I will create more soon too.

**Comment by oderinde300** [comment]
Okay. Thanks @DamyanBG
