### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#124]
Add a icon to the header - on the left side of sign up. Show this icon only if the user is signed in. The icon have to be related to messages, chat. When the user clicks on this icon, he must be redirected to /chat-history. On this route make a page. In this page map all interlocutors, which are returned from the back end on point /message/history/{user_id}. Makes the names as links. These links must to redirect to /chat?interlocutorId={interlocutorId}?names={names}.

**Comment by DamyanBG** [comment]
Only I can assign tasks.

**Comment by DamyanBG** [comment]
First I want to say thank you for joining in the project! Bare in mind that the back end is still not implemented! When you get to the point to make the request, ping me!

**Comment by oderinde300** [comment]
Am I allowed to install a third-party library like react-icons?

**Comment by DamyanBG** [comment]
Yes, you are

**Comment by oderinde300** [comment]
Alright.

**Comment by oderinde300** [comment]
Hi, I need to make a request can I get an endpoint to use.

**Comment by DamyanBG** [comment]
Read the requirements and take a look into urls.js file in the codebase. Bare in mind that the functionality in the back end is not implemented, so you have to mock up the request. Example for response body is:
[
  {id: "3234534", names: "John Bond"},
{id: "3234531", names: "John Band"},
{id: "3234533", names: "John Stronger"},
{id: "3234534", names: "John Somebody"},
]

**Comment by oderinde300** [comment]
Ok. I read the requirements of the issue. I should create a mock backend for the messages endpoint with the data in this format right
[
{id: "3234534", names: "John Bond"},
{id: "3234531", names: "John Band"},
{id: "3234533", names: "John Stronger"},
{id: "3234534", names: "John Somebody"},
]

**Comment by DamyanBG** [comment]
Or you can help with https://github.com/DamyanBG/real-estate-nodejs-be/issues/136

This is the issue in the back end.

**Comment by oderinde300** [comment]
No, am not good with the backend stuff.  Just confused about what you meant by "mock-up the request"

**Comment by DamyanBG** [comment]
Then wait me, I will implement the back end logic.

**Comment by oderinde300** [comment]
Okay. I will wait for you to implement the backend logic.

**Comment by oderinde300** [comment]
Will you be implementing it today?

**Comment by DamyanBG** [comment]
I am done, just wait to merge and deploy

**Comment by oderinde300** [comment]
Alright. I guess I can make use of the endpoint now right?

**Comment by DamyanBG** [comment]
yes

**Comment by oderinde300** [comment]
Alright. Thanks
