### ISSUE TITLE
Request meeting

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#131]
On Home and Land details pages, add a button Request meeting. When the user clicks on that button, redirect him to /create-meeting page. Add a parameter to the URL createWithId which is equal to the owner_id from the details page.

**Comment by 2201monesh** [comment]
Hey @DamyanBG can you assign this issue to me.

**Comment by DamyanBG** [comment]
Of course

**Comment by 2201monesh** [comment]
Hey @DamyanBG I have raised a PR #157

**Comment by DamyanBG** [comment]
Can you read again the descriptions and do your work again? If you have some questions, you can ask me.
