### ISSUE TITLE
Create visitation button

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#135]
On Home and Land details page add create visitation button. Show this button only if the current user is the owner of the Home or Land. When the user clicks on that button, redirect him to /create-visitation. Add 2 parameters - kind which have to be equal to home or land and id, which is the id of the Home or Land.

**Comment by felonious-boop** [comment]
Hi there! Could I take this?

**Comment by DamyanBG** [comment]
Yes

**Comment by DamyanBG** [comment]
@felonious-boop any progress?
