### ISSUE TITLE
Map in Home Details

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#143]
If Home contains lat and lon, add a map and show the exact place.

**Comment by Safiullah-98** [comment]
Please let me know the exact detail, so that i can contribute a better solution

**Comment by DamyanBG** [comment]
Okay. Take a look at HomeDetails.js component. There is a state object named homeDetails. This object holds the data received from the back end. If this object contains latitude and longitude, show a map (GoogleMap or some other kind) and add a pin on the position of the Home.

**Comment by Safiullah-98** [comment]
okay i will let you know once done! thanks...
