### ISSUE TITLE
Authorization for creating Home or Land

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#144]
When an user go to Sell and clicks on Land or Home, he is redirected to creating pages. If the user is not signed in or the user do not have seller role, please, show a message:

You have to be signed in as seller. If you are signed in already, upgrade to seller role.

**Comment by oderinde300** [comment]
Am interested in solving this issue.

**Comment by DamyanBG** [comment]
Assigned

**Comment by oderinde300** [comment]
Alrigth
