### ISSUE TITLE
Signup form validation

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#146]
We have to implement validation for the signup form. This is the first validation implemented in the application. Because of that, here we have to decide what kind of validation to use.

The requirements are:

1. First name have to be at least 3 characters long and max 150 characters.
2. Last name have the same requirements as first name
3. Email have to be valid email. I think some regex will be good choice.
4. Phone number have to be at least 3 characters.
5. Password must contains at least 6 characters and log max 150 characters.

If the user do not input correct data, show error message under the field, which do not contain validate data.

**Comment by AlfiyaSiddique** [comment]
Hello **@DamyanBG** 

I would like to work on this issue.

**Comment by DamyanBG** [comment]
Ok, I will assign this issue to you!

**Comment by Safiullah-98** [comment]
hey is the issue is resolved yet? i want to work on it!

**Comment by AlfiyaSiddique** [comment]
> hey is the issue is resolved yet? i want to work on it!

yes, it is resolved, I did all the required changes. I am almost ready to commit to this issue.

**Comment by DamyanBG** [comment]
@Safiullah-98 Thank you for the interest, but as you can see this issue is assigned. I will create more tasks related to the form validation, but first I want to clean up validation for one form and after that we will reuse the same style everywhere.

**Comment by DamyanBG** [comment]
@AlfiyaSiddique Hello, I was able to send request with first name including more than 150 characters.

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique Hello, I was able to send request with first name including more than 150 characters.

okay, I'll do the changes

**Comment by DamyanBG** [comment]
btw I have one remark - your code formatting is not good. For that we have prettier - if you are not sure how to format your code, use prettier.

**Comment by DamyanBG** [comment]
I merged your code without to take a look. Just tested and saw that I am able to send request without to input first name.

**Comment by DamyanBG** [comment]
Hey, nice work! I have some remarks and I made some refactoring. You can see the latest code.

**Comment by DamyanBG** [comment]
@AlfiyaSiddique I am inviting you to join on my new project , if you have time https://github.com/DamyanBG/cat-of-the-day-front-end

**Comment by AlfiyaSiddique** [comment]
I would definitely contribute as much as possible.👍🏻
