### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#15]
Make on route /about new page which will include some information about the project. There can be written that this is open source project and it aims people who wants to train their Javascript skills. At the end the project will be hosted by me in Azure. Write the main idea behind the project from the README. Leave links to GitHub repositories for the front end and for the back end. Later I will add the links.

**Comment by Badrri-Narayanan** [comment]
Hi @DamyanBG , can you please assign me this issue?

**Comment by DamyanBG** [comment]
Yes.

**Comment by DamyanBG** [comment]
Please, add links to thus repo, to the back end repo, to the YouTube video. You can find links in the ReadMe file.

**Comment by DamyanBG** [comment]
@Badrri-Narayanan  Thank you for your effort!
