### ISSUE TITLE
Better style for News

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#163]
Add better style to News. I do not have any requirements, just be creative!

**Comment by Chris5613** [comment]
Hey! may I take this?

**Comment by DamyanBG** [comment]
Yes.

**Comment by Chris5613** [comment]
Hey, I changed some styles around to make the text fit the page a little better than being stranded in the middle. I do want to mention that I see some errors in the console unrelated to my changes that may warrant a look.  I also understand there are no requirements for this issue but if there's something specific you would want to see let me know.

**Comment by DamyanBG** [comment]
Hello,

For this issue just change the style. If you see some errors, you can feel free to open new issue, assign it and make a PR for it. I want to keep tracking of the work.
