### ISSUE TITLE
Sign in form validation

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#164]
Wait for #146 to be done and examine the codebase behind the validation created regarding this issue and add similar for Sign in form.

**Comment by oderinde300** [comment]
I am interested in working on this issue.

**Comment by DamyanBG** [comment]
I think it is good idea to take only 1 issue per time. Please, choose which one.

**Comment by oderinde300** [comment]
Yes. I made the mistake, I will go for issue 165.
