### ISSUE TITLE
Create Home form validation

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#165]
Add validation form create Home form. Follow these rules:

- title - required, min 3 chars max 150
- city - required, min 3 chars max 150
- address - required, min 3 chars max 150
- longitude - max 50 chars
- latitude - max 50 chars
- price - required, valid integer, max 50 chars
- year - required, valid integer, max 5 chars
- description - required, min 5 chars, max 150

**Comment by oderinde300** [comment]
I am interested in fixing this issue. Can use any form validation library I want

**Comment by oderinde300** [comment]
I am interested in fixing this issue. Can I use any form validation library I want?

**Comment by DamyanBG** [comment]
Okay, so we are here for learning, so use whatever you want. But I will give you additional task. When you are ready, make you pull request. After that, make another branch from it and try to implement tests using the library which you suggested. After that make other PR in draft status, so we can discuss which library to use and why.

**Comment by oderinde300** [comment]
Alright. Lot of work

**Comment by DamyanBG** [comment]
I mean tests only for the form validation which you will implement, not for the hole page.

**Comment by oderinde300** [comment]
Oh! Okay.

**Comment by DamyanBG** [comment]
Hello, @oderinde300 !

2 remarks for you - first, when you have to resolve code conflicts, please, do it good. Check is everything working. Usually developers are working in teams and there a lot of cases of merge conflicts. When you make some code changes, make sure that you didn't break the hole application and after that the code of your repository buddy.

Second - I fetched your branch before the conflict resolving and tested your work. At all everything works nice, expect edit. When the user opens edit home he have to see the current information. With your initial values object, the user now sees empty fields, because you are setting '' values everywhere. You did not implemented the logic when you will have some data as initial values.

One more - try to think more about naming and where to place your code. Do you think formikFile.js is a good name? Do you have to explicitly write that is a file? 

Think more and for the validations - isn't better to have validation.js file where we can store all validations for all fields? Do you really need it? In edit form you can just pass initialValues={homeInfo) and everything will works. 

I can say more things, but at all I think this is enough. Usually Formik is the easiest way to validate forms in React. Let's not use the easiest way here, let's learn something new, so I will want you to implement validations in other way.

**Comment by oderinde300** [comment]
Hi @DamyanBG, thanks for the corrections. I will work on them and redo the validation in another way. And I will pay more attention to the names I give my files.

**Comment by oderinde300** [comment]
Hi, @DamyanBG regarding the test. I can't write the test using vitest unless the react project was initialized with vite.

**Comment by DamyanBG** [comment]
Okay.

**Comment by oderinde300** [comment]
So, can I apply to work on another task,

**Comment by DamyanBG** [comment]
Yes, I have open tasks for styling.

**Comment by oderinde300** [comment]
Okay. I will check it out in the issues now.
