### ISSUE TITLE
Create Land form validation

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#166]
Follow the style of validation which is already implemented.

Rules:
 - name - required, min 3 chars, max 150
 - place - required, min 3 chars, max 150
 - price - required, valid integer, max 50 chars
 - description - required, min 5 chars, max 150 chars
 - longitude - max 100 chars
 - latitude - max 100 chars

**Comment by edesuccess54** [comment]
@DamyanBG i believe this validation should be done before sending request to the server right? and what do you mean when. you say "Follow the style of validation which is already implemented."?

**Comment by DamyanBG** [comment]
Hello, @edesuccess54 

Yes, I mean to validate input data before to send it to the back end. For example - if the user do not input name and wants to send the request, instead of sending bad request, show a message what exactly he forget to write.

By follow the style of validation I mean that in parallels 2 people are working on different forms from the application. But this night I changed my mind. Implement it by yourself. At the final we will choose the best way and we will make a refactoring.

**Comment by edesuccess54** [comment]
alright
