### ISSUE TITLE
empty chat message

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#167]
I was able to send empty chat message in the chat page. Please, fix that.

**Comment by AlfiyaSiddique** [comment]
Hello **@DamyanBG** 

I Want to work on this bug.
If the user tries to send an empty message, should a pop-up appears that informs the user to write the message first and then send it?
Or do I just have to prevent empty messages from being post.

**Comment by DamyanBG** [comment]
Just prevent and that's all.
