### ISSUE TITLE
Choosing test framework vote

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#169]
It is time to start to test our application. First of all, lets pick up test framework. This will be open for 1 week. I will close it on 31.01.

**Comment by oderinde300** [comment]
Vitest

**Comment by alivadjid** [comment]
Vitest: 1. Easy install, easy use. 2. Jest duplication.
What kind of test will be? Unit, e2e?

**Comment by DamyanBG** [comment]
> Vitest: 1. Easy install, easy use. 2. Jest duplication. What kind of test will be? Unit, e2e?

What kind do you suggest?

**Comment by oderinde300** [comment]
I think testing individual components will be good. so Unit test. But I think vitest can only be used if the react app was initialized with  vite @alivadjid

**Comment by alivadjid** [comment]
@DamyanBG  I agree with @oderinde300 to make unit tests for components. 
And it's true. For using vitest  project requires Vite

**Comment by DamyanBG** [comment]
Okay, lets use Jest.
