### ISSUE TITLE
Header style challenge

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#172]
Change the style of the header. You can do whatever you want, just keep the background color same. 

The main idea is to practice and learn, so I will not assign the issue for now to anybody. I will wait for few people to try to make nice looking header, at the final I will choose the best one. 

When you are ready add a PR + image of the header as a comment here.

**Comment by hparashar27** [comment]
hey @DamyanBG  if it's still open can i start working on it

**Comment by DamyanBG** [comment]
Yes

**Comment by tihomirtx88** [comment]
Hey @hparashar27 are you working under this issue ?

**Comment by hparashar27** [comment]
Yes , recently i am working on it

**Comment by DamyanBG** [comment]
@tihomirtx88 @hparashar27 everybody can work om this issue. The main idea is to practice and learn. I would want few people to practice on this issue. At the end all of you can see and compare solutions.
