### ISSUE TITLE
remove background color from the project

### ISSUE THREAD

**Issue by edesuccess54** [DamyanBG/real-estate-react-app#185]
the project is not looking great at all with the background applied to it

**Comment by DamyanBG** [comment]
What do you mean and what do you suggest?

**Comment by edesuccess54** [comment]
i mean the background color applied to the area i marked on the image below is inappropriate in my opinion. i feel it looks more great the way it was before the background color

![Screen Shot 2023-01-16 at 10 04 45 PM](https://user-images.githubusercontent.com/87667603/212765980-94964acd-dc41-4060-b098-932b59d69afe.png)

**Comment by DamyanBG** [comment]
You have the code in your hands. You are free to make changes.
