### ISSUE TITLE
UI project packages

### ISSUE THREAD

**Issue by alivadjid** [DamyanBG/real-estate-react-app#189]
For best experience maybe let's think about use own ui project packages? 
It is possible to create and store it here in this project github.
What do you think about it?

p.s. don't find discussions and open this issue for discussion.
don't see any labels. Maybe should add them too.

**Comment by DamyanBG** [comment]
Can you explain your idea in details , code examples and to say the benefits of doing that? I mean, I do that mostly for learning purpose and I think it is good to have arguments why are doing something.

**Comment by alivadjid** [comment]
Yes of corse.
For example in our project used button
FormSubmitButton.js
```
export default function FormSubmitButton() {
    return (
        <button type="submit" className="submit_btn">
            Submit
        </button>
    );
}
```
I think for practise we can move this component into the separate own package. 
And start making something like bootstrap or same ui library. Add props, make styles.

**Comment by DamyanBG** [comment]
I think I got your idea.
