### ISSUE TITLE
Team meeting/project organization.

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#192]
I can see that we are growing. I think monthly or on every 2 weeks to make a team meeting if somebody wants to join or to make videos with updates and ideas. Then I will upload the video and even if nobody have a chance to join into the meeting, I will just say the updates, the plans and open topics for comments. 

What do you think for the idea? Do you have some suggestions?

 @oderinde300 @alivadjid @tihomirtx88

**Comment by oderinde300** [comment]
Great Idea. I would love to join the meetings.

**Comment by DamyanBG** [comment]
@edesuccess54

**Comment by tihomirtx88** [comment]
If i am not on my workplace i will join also.

**Comment by edesuccess54** [comment]
this is actually a great idea. if we must work as a team, then on the day scheduled for the meeting, everyone should make they self available. we need a UI/UX designer in the team

**Comment by DamyanBG** [comment]
Yes, UI/UX is my weak point. Okay, guys, at which weekday you are free? Saturday, Sunday? At the morning, at the night?

**Comment by oderinde300** [comment]
Saturday at night

**Comment by edesuccess54** [comment]
I'm free basically free any day during the week since I don't have a full time job at the moment.

**Comment by edesuccess54** [comment]
I think Saturday is perfect. We need to consider the timezones we're all in also

**Comment by DamyanBG** [comment]
Cool. I'm in Sofia timezone which is +02

**Comment by alivadjid** [comment]
> Cool. I'm in Sofia timezone which is +02

my GMT+03:00

**Comment by edesuccess54** [comment]
Mine GMT+1

**Comment by alivadjid** [comment]
What about saturday on 15.00  GMT on discord?

**Comment by edesuccess54** [comment]
Actually I feel we should run a kind of pool with two different option. The option should be in such a way that it will not fall within the midnight of anyone.Then everyone will make themselves available around the time with the highest percentage. Thanks

**Comment by oderinde300** [comment]
Mine GMT+01

**Comment by DamyanBG** [comment]
> What about saturday on 15.00 GMT on discord?

I agree.

**Comment by DamyanBG** [comment]
https://www.youtube.com/watch?v=19r1q6-LGcQ

Please, watch this video before the meeting.

**Comment by edesuccess54** [comment]
> > What about saturday on 15.00 GMT on discord?
> 
> I agree.

i agree too

**Comment by oderinde300** [comment]
> 
seen

**Comment by DamyanBG** [comment]
Who will make a discord group?

**Comment by oderinde300** [comment]
> Who will make a discord group?

I will make the group

**Comment by oderinde300** [comment]
I need our discord usernames name so I can send the group chat invite link

**Comment by edesuccess54** [comment]
You can create a group now, as the community grows we can make a server

**Comment by oderinde300** [comment]
I think it would be nice to create both. The server can be announcements while the private chat for meetings. Because I don't see the essence of a meeting if we are not allowed to make use of voice notes and video calls.

**Comment by DamyanBG** [comment]
I think it will be good to be able to share the screen. I want to show you something.

**Comment by DamyanBG** [comment]
DamyanDimitrov#7990

**Comment by oderinde300** [comment]
> I think it will be good to be able to share the screen. I want to show you something.

True

**Comment by oderinde300** [comment]
Here is the discord server link

[https://discord.gg/j6GkDbWH](https://discord.gg/j6GkDbWH)

**Comment by DamyanBG** [comment]
Hi everybody!

We made our first meeting today :) I want to share in few words what we discussed for these who wasn't able to join:

- @alivadjid and @oderinde300 suggested to find UI/UX designer
- @oderinde300 suggested to make specific issues for UI/UX designers with 'good first issue' label
- @alivadjid suggested one of his friends to join
- I showed the plan for the next few enhancements and from where I take ideas
- I showed the progress in the back end repository

I just created few issues which are related to UI/UX. I hope soon to have our UI/UX designer :)

The real estate websites from which I take ideas are:
- https://www.trulia.com/
- https://www.zillow.com/
- https://www.realtor.com/
- https://fsbo.com/

**Comment by edesuccess54** [comment]
Great, it's unfortunate I was unavailable to join the meeting

**Comment by AyoubTahir** [comment]
Same for me, I am working on the backend and I missed it, can you next time post it on the backend too :)

**Comment by DamyanBG** [comment]
Ok

**Comment by Aarize29** [comment]
Can I join your team please!!

I have a good experience on working with reactjs

**Comment by oderinde300** [comment]
Sure. It’s an open source project

**Comment by Aarize29** [comment]
> Sure. It’s an open source project

Thank you sir

**Comment by DamyanBG** [comment]
Guys,

I think the project is already at his end. I think the functionality is very good, just the style have to be changed, but that is not so important. 

Soon I will stop all services and deployments.

It was really nice to work with you. I earned good experience as Dev Team Lead, Architect of a small applications, DevOps skills.

Of course that is not the end of developing, I will start 2 or 3 new projects these days, follow my profile for more information, if you want to join!

See ya!

**Comment by edesuccess54** [comment]
> Guys,
> 
> I think the project is already at his end. I think the functionality is very good, just the style have to be changed, but that is not so important.
> 
> Soon I will stop all services and deployments.
> 
> It was really nice to work with you. I earned good experience as Dev Team Lead, Architect of a small applications, DevOps skills.
> 
> Of course that is not the end of developing, I will start 2 or 3 new projects these days, follow my profile for more information, if you want to join!
> 
> See ya!

Unfortunately, I was not able to follow along on the project. I have a couple of things going on, on my end but I'm happy the project is at this level

**Comment by DamyanBG** [comment]
@edesuccess54 @alivadjid @tihomirtx88 @AyoubTahir I am inviting you to join on my new project - https://github.com/DamyanBG/cat-of-the-day-front-end

**Comment by oderinde300** [comment]
Great. Am in 🎉

**Comment by alivadjid** [comment]
me too! :+1:
