### ISSUE TITLE
Edit Land bug

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#196]
When the user is not signed in he is able to edit Land and signed in user is able to edit lands which do not belong to him.

**Comment by AyoubTahir** [comment]
I think someone working on this one, can you provide me with a list of bugs or features that need implementation on this project so I can begin working on them, whether they be backend or frontend related?

**Comment by DamyanBG** [comment]
Hello,

First I want to say welcome to the project!

This is the front end repository and everything here is related to front end. We are using React. Here the case is that - if an user is not the owner of the Land, he do not have to be able to edit it.

About the list - actually the issues list is the list with bugs and enhancements, which have to be made/fixed.
