### ISSUE TITLE
Authentication and authorization for Lands operations

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#199]
In the back end we are almost done with auth related logic. For that we have to send the token with the requests.

**Comment by AyoubTahir** [comment]
After I finish the test in the backend, I will do this one. I already completed the tests for land's authorization and authentication and now I am working on the tests for home.

**Comment by AyoubTahir** [comment]
So if we want to send the token with every request, we need to use Axios or another library, so that we can use interceptors but the fetch is used all over the place it's not easy to replace it, we could do a fetch custom interceptor but I think its a bad practice.
what are your opinions?

**Comment by DamyanBG** [comment]
I think for now you can add Authorization: Bearer {token} where us needed. In future we will start refactoring, we will decide which way to use and we will adapt it everywhere.

**Comment by AyoubTahir** [comment]
Ok

**Comment by DamyanBG** [comment]
@AyoubTahir how is going?
