### ISSUE TITLE
Main page style UI/UX 

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#203]

**Comment by Rustimbest** [comment]
assıgne me,please

**Comment by DamyanBG** [comment]
Hello,
Tomorrow I will provide more information about the requirements.

**Comment by Rustimbest** [comment]
Okay, I will show

**Comment by DamyanBG** [comment]
Ok, show me

**Comment by Rustimbest** [comment]
end a site for ui example, please
 
 
С уважением,
Руслан Тимаев
4-36*
***@***.***

**Comment by DamyanBG** [comment]
I think you can find by yourself and show us. We do not have any special requirements. Just be creative.

**Comment by Rustimbest** [comment]
What i got at this moment
https://www.figma.com/proto/YA2RCPxcNwwa6xfw2qPdEw/Untitled?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1

**Comment by Rustimbest** [comment]
https://www.figma.com/proto/YA2RCPxcNwwa6xfw2qPdEw/Untitled?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1 
1440 х 1024 for Desktop...

**Comment by DamyanBG** [comment]
Hey, thats look really cool

**Comment by alivadjid** [comment]
+1, suggest using this ui

**Comment by DamyanBG** [comment]
Thanks @Rustimbest for the great style!
