### ISSUE TITLE
Footer UI/UX style

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#204]

**Comment by Rustimbest** [comment]
What i got at this moment
"https://www.figma.com/proto/YA2RCPxcNwwa6xfw2qPdEw/Untitled?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2" footer

**Comment by alivadjid** [comment]
Looks fine

**Comment by alivadjid** [comment]
> What i got at this moment "https://www.figma.com/proto/YA2RCPxcNwwa6xfw2qPdEw/Untitled?node-id=1%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2" footer

Looks fine

**Comment by DamyanBG** [comment]
I like it too

**Comment by DamyanBG** [comment]
Thanks to @Rustimbest for the great style!
