### ISSUE TITLE
Latest News

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#21]
On route /news make a page, where few articles related to real estate will be shown. You can take 10 news from the back end with GET request on /news. Feel free to make whatever styling you wish and even you can not show all 10 news, if that not feel the style which you want to make.

**Comment by alivadjid** [comment]
Assigned to me, please

**Comment by DamyanBG** [comment]
Assigned!

**Comment by alivadjid** [comment]
When trying to get data from `/news` got the error 
![изображение](https://user-images.githubusercontent.com/52418132/210889016-6e849fbc-d2c6-42f2-972d-3b79b770c598.png)

**Comment by DamyanBG** [comment]
Looks like the API key is not working. Tomorrow I will fix it. If you dont want to wait you can clone the back end repository and develop on local.

**Comment by alivadjid** [comment]
I'll try

**Comment by DamyanBG** [comment]
You have to create .env file and inside to add the variables. For the database you have to add local mongodb database.

**Comment by DamyanBG** [comment]
I fixed it on Azure.

**Comment by DamyanBG** [comment]
Thank you for the effort!
