### ISSUE TITLE
Add validations to edit Home

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#212]

**Comment by tushar1-000** [comment]
Hi I am interested to contribute to this

**Comment by DamyanBG** [comment]
Okay. There are validations implemented for create Home and Land, so you can use them.

**Comment by DamyanBG** [comment]
@tushar1-000 any progress?

**Comment by tushar1-000** [comment]
sorry man, I did not get a notification about those messages. But from today onwards I will start on this.  Can you list down things that you want me to accomplish?
