### ISSUE TITLE
Display visitations for properties

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#221]
Now every Home or Land can have visitations. Display visitations. When somebody takes this issue I will provide more info.

**Comment by oderinde300** [comment]
I want to be assigned this issue.

**Comment by aarishmkhan** [comment]
Hey, I can work on this issue. Please assign this issue to me

**Comment by aarishmkhan** [comment]
I have set up the repo locally

**Comment by DamyanBG** [comment]
Hey, @oderinde300, lets give turn on the newcomer

**Comment by oderinde300** [comment]
Okay then @DamyanBG

**Comment by DamyanBG** [comment]
@aarishmkhan First let me say welcome to the project! I will write you the explicit requirements after 1 hour. Here is lunch time, so I want to eat something and I will get back.

Usually the idea is to list the visitations on Home and Land details pages. You can take a look at the project until I give you more details.

**Comment by DamyanBG** [comment]
The requirements are:

On Home details page you have to show all visitations for this Home. For that you have to make a GET request to the back end on route /visitation/home/{homeId}. The back end will return all visitations related to this homeId. 

For Land it is the same logic, just the route have to be /visitation/land/{landId}.

Bare in mind that the functionality on the back end is not ready. I will implement it today or tomorrow and then we will check for bugs.

**Comment by abhijithp05** [comment]
@DamyanBG Is someone working on it or I can pick it up?

**Comment by oderinde300** [comment]
The issue has been assigned
