### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#232]
We need to have Pagination functionality. Implement for now this functionality for Homes and Lands list.

**Comment by numofran6** [comment]
I can take this task on. You can assign it to me.
How many homes/lands do you want to be displayed at a time?

**Comment by numofran6** [comment]
Okay. I working on it

**Comment by numofran6** [comment]
## Progress

- [x] Forked project and started working on pagination
- [ ] Pagination applied
- [ ] Pull request set

**Comment by DamyanBG** [comment]
good work
