### ISSUE TITLE
Profanity check

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#234]
We have to implement profanity check functionality. Implement for now that for Home creation page and after that we will copy the functionality for the other places.

**Comment by Saran-pariyar** [comment]
sir do you mean I should check for bad words in create-home page when filling out the form and it will show the red text warning when we enter bad words?

![image](https://user-images.githubusercontent.com/86418083/218262802-ff8a0a0e-7481-4105-b69e-c4022cd80587.png)

**Comment by DamyanBG** [comment]
Something like that, yes

**Comment by Saran-pariyar** [comment]
> Something like that, yes

thanks!
Can you please assign me this? I  will work on it

**Comment by DamyanBG** [comment]
OK

**Comment by DamyanBG** [comment]
I can see that there is no progress. I will implement that feature these days.

**Comment by DamyanBG** [comment]
Done by me ;)
