### ISSUE TITLE
Add project Link to About section

### ISSUE THREAD

**Issue by numofran6** [DamyanBG/real-estate-react-app#238]
For easy access to the projects URL, please add link to the github About section

**Comment by DamyanBG** [comment]
![about](https://user-images.githubusercontent.com/93829069/219290171-d3cb9f8c-cca5-4c86-8bbd-98a4cf7305ed.png)

**Comment by numofran6** [comment]
I mean this About Section

![Screenshot (604)](https://user-images.githubusercontent.com/68471958/219338648-e727b857-82e8-4454-8392-881a1eb40596.png)

**Comment by DamyanBG** [comment]
![Uploading Screenshot 2023-02-16 131036.png…]()

**Comment by DamyanBG** [comment]
![Screenshot 2023-02-16 131036](https://user-images.githubusercontent.com/93829069/219349602-a6d5edbd-faa2-4bd2-9650-1cd526936ae0.png)
