### ISSUE TITLE
Display views 

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#239]
There is a functionality which counts how much times a home and land is viewed. Show the number on details pages for Homes and Lands. If the value do not come, open an issue to the back end project.

**Comment by elenistvr** [comment]
@DamyanBG  can you provide the admin credentials and the path to admin page? I also have trouble generally signing up with an email.

**Comment by DamyanBG** [comment]
> @DamyanBG  can you provide the admin credentials and the path to admin page? I also have trouble generally signing up with an email.

Hello,

I am glad that you want to contribute to the project!

I stopped the deployment of the back end. There is a link to the back end repository. You can make you own set up on local.

**Comment by elenistvr** [comment]
> > @DamyanBG  can you provide the admin credentials and the path to admin page? I also have trouble generally signing up with an email.
> 
> Hello,
> 
> I am glad that you want to contribute to the project!
> 
> I stopped the deployment of the back end. There is a link to the back end repository. You can make you own set up on local.

Hi 👋 , ok thank you, I will check it.
