### ISSUE TITLE
Do not show pagination if entries are not much

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#240]
Do not show the pagination on Homes and Lands if the entries are not much.

**Comment by numofran6** [comment]
I can take this issue

**Comment by DamyanBG** [comment]
OK

**Comment by abhinavrathore25** [comment]
Hi, is the issue resolved?

**Comment by numofran6** [comment]
> Hi, is the issue resolved?

I believe so, Abhinav

**Comment by DamyanBG** [comment]
Yes, it is solved.
