### ISSUE TITLE
Add pagination to admin panel

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#241]
Add the pagination to the admin panel, there are management pages where the entries are mapped. Use the existing logic for pagination.

Use admin profile credentials:
admin@abv.bg
123456

**Comment by numofran6** [comment]
I'll take this task

**Comment by DamyanBG** [comment]
OK

**Comment by numofran6** [comment]
Log in credentials for admin profile not working

**Comment by numofran6** [comment]
And please provide route to the admin page that needs pagination.
