### ISSUE TITLE
Add exception for the Lands photos

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#258]
If the photo_url returns error, show the default Land image

**Comment by Jonnie-Dev** [comment]
Hi there, would love to help with this

**Comment by DamyanBG** [comment]
Maybe you have to start the back end

**Comment by DamyanBG** [comment]
![Screenshot_20230805_161717.jpg](https://github.com/DamyanBG/real-estate-react-app/assets/93829069/45a59dea-ae9e-4fe6-a952-b09645961ca5)

This is the path for the default image
