### ISSUE TITLE
Edit Meeting

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#261]
We need to have page for edit meeting events.

**Comment by DamyanBG** [comment]
Hello,

I am glad to hear that you have interest.

Right now I think we have functionality to create meetings, not to edit already created meeting.

Take a look at Meeting component and if you have more questions - ask me.

If you have problems with setting up the project on local - ping me.

**Comment by DianaSemanova** [comment]
Thank you for your answer. I want to ask if I should also work on backend. If yes should I use this?  https://github.com/DamyanBG/real-estate-nodejs-be/

**Comment by DamyanBG** [comment]
> Thank you for your answer. I want to ask if I should also work on backend. If yes should I use this? https://github.com/DamyanBG/real-estate-nodejs-be/
Actually already no. I switched the back end to Python.

**Comment by DamyanBG** [comment]
https://github.com/DamyanBG/real-estate-integration

Take a look of this repository.

This integration repository for the project. You can use this with Docker to run the back end with the database, without to install Python and PostgreSQL on your computer. Right now I will update the documentation. If you have further questions - ask me.
