### ISSUE TITLE
Disable button after submit

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#267]
When the user post a home, disable the button until response is received. Make the same for edit home, create land and edit land.

**Comment by ayobamiseun** [comment]
can i contribute to this

**Comment by DamyanBG** [comment]
Okay, I will assign it to you.

**Comment by sagargoyal-bit** [comment]
is it solved? I would also like to work on it.

**Comment by DamyanBG** [comment]
The issue is still not solved.

**Comment by Srenky** [comment]
Hi hi, I'd like to work on this issue if it's still available. I have a uni assignment to make some contribution to OSS and this issue caught my eye.

**Comment by DamyanBG** [comment]
Hello,

Feel free to make PR. This issue is simple, so when you make a PR I will assign the work to you.
