### ISSUE TITLE
Add style to the initial page

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#27]
Add style to the initial page. You can modify whatever you want, just keep some homes to be visible on the page. You can use the example photo in /images instead of the real photos, which will come later. 

Simply add a screenshot here of the new style, I want to see it before to assign the task.

**Comment by edesuccess54** [comment]
@DamyanBG look what i have got for the initial page

![Screen Shot 2023-01-02 at 9 16 45 AM](https://user-images.githubusercontent.com/87667603/210207666-b5274bff-58c7-4a97-98f0-9760e63e210e.png)

**Comment by DamyanBG** [comment]
Looks good, but not completely. I would want to have some section after the header with some description about the website. After that we can map few houses - maybe 3 till 5. Depends on the view. I will upload some photos for inspiration.

**Comment by DamyanBG** [comment]
![DamyanDimitrov_website_for_real_estate_modern_efc653db-f617-4c73-ad1d-fb61c57c9b81](https://user-images.githubusercontent.com/93829069/210208593-afbb6bcd-40d9-45ed-b9fe-f4495a161e54.png)

**Comment by DamyanBG** [comment]
![df0b8183721140e283287b52d64edea1](https://user-images.githubusercontent.com/93829069/210208672-8593a2b5-de9f-44fc-afa7-cafc8449347e.png)

**Comment by DamyanBG** [comment]
Look at the last one. On the left side there is a nice header, after that a section with a nice photo background and some text. After that there are 4 mapped Homes with the real photos. I will try these days to make the functionality on the back end and on the front end to be able to upload real photos, but for now we can mock up the photos.

**Comment by edesuccess54** [comment]
okay i get it now, i will work on it and get back

**Comment by DamyanBG** [comment]
You can use some of the photos which I provided. Just crop them with some image editor. For the text use the text from the description in this issue or something similar
