### ISSUE TITLE
Sign In click 

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#275]
When the user is not signed in and clicks on Sign In link, logout request is triggered. That is not good behavior.

**Comment by abdosahsah** [comment]
Hi, Can you assign me to fix the issue

**Comment by DamyanBG** [comment]
I will assign it when I see pull request. A lot of people are asking to do some features, but after that they are not active.

**Comment by DamyanBG** [comment]
Fixed by @StrixV54
