### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ayobamiseun** [DamyanBG/real-estate-react-app#288]
<img width="1437" alt="Screenshot 2023-10-02 at 10 08 02" src="https://github.com/DamyanBG/real-estate-react-app/assets/66267222/da50ee79-c74c-4128-ab72-bea5e0cacd42">
Compiled with problems:

**Comment by DamyanBG** [comment]
Today I will try fresh install and will check.

**Comment by ayobamiseun** [comment]
any lock regarding this

**Comment by DamyanBG** [comment]
There is a contributor which just made a lot of changes - migrated the app to Vite. I will reinstall everything right now and will tell you.

**Comment by DamyanBG** [comment]
I have no idea what is going on your side. Please, make new install.

**Comment by DamyanBG** [comment]
I think you have to clone the project again and make fresh install. If you still have error, we can make a call.
