### ISSUE TITLE
Rent nav link and Rent page

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#30]
Make Rent on the header link to /rent. On route /rent implement simple page, which says something like - Under construction, under implementation. Add some photo, drawing or whatever you want, just make sure that we can use it.

**Comment by maddy020** [comment]
Please assins this issue to me

**Comment by maddy020** [comment]
> Please assign this issue to me

**Comment by DamyanBG** [comment]
Done, Thanks to @maddy020
