### ISSUE TITLE
Home details

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#317]
Split components on smaller components

**Comment by walleeva2018** [comment]
Can I work on this @DamyanBG ?

**Comment by DamyanBG** [comment]
> Can I work on this @DamyanBG ?

Yes, of course

**Comment by walleeva2018** [comment]
Hey I am having some trouble setting up the back-end. What should I put `AZURE_DATABASE_CONNECTION_STRING` To this variable. I run the server it expects some mongoDB url. How can I get this running?

**Comment by DamyanBG** [comment]
@walleeva2018  you can just use 'npm start'. An instance of the back end is deployed and this script connect the FE with it.
