### ISSUE TITLE
After successful  sign in

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#328]
After successful sign in, I am pretty sure that the back end returns the token. Use this token and log in the user.

If the back end do not return the back end, ping me.

**Comment by Pulkitxm** [comment]
Hey I think the backend is not returning any response

![image](https://github.com/DamyanBG/real-estate-react-app/assets/65671483/850b6005-c558-4c29-9abf-83fa0aa5915b)

![image](https://github.com/DamyanBG/real-estate-react-app/assets/65671483/5ce222d0-917b-4eff-bb86-79a2c5ee1255)

**Comment by DamyanBG** [comment]
Hello @Pulkitxm ,

First I want to say welcome to the project!

Let me check the back end and I will get back to you,

**Comment by DamyanBG** [comment]
![image](https://github.com/DamyanBG/real-estate-react-app/assets/93829069/08a95243-4917-40a1-a75f-b789e6524e26)

Actually we have an answer from the back end with the needed information. The file which have to be edited is SignInPage.jsx 
If you have further questions - ping me

**Comment by DamyanBG** [comment]
@Pulkitxm  bare in mind that I deployed the back end in Render and the response time can be long.
