### ISSUE TITLE
Sign in page

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#33]
On route /signin implement page with form, which contains email and password. Send them to /login route on the back end with post request. When you receive the token, store it in the cookies. Store the userId in the localstorage. Redirect the user to '/' after success login. Show a message wrong email or password if something is wrong.

**Comment by ashwaryy** [comment]
Would like to do, if not assigned already.

**Comment by DamyanBG** [comment]
@ashwaryy Welcome to the project! I am glad that you want to contribute! Just one additional criteria:I think the back end return some token. If you can, store it as a cookie.
