### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#345]
![image](https://github.com/DamyanBG/real-estate-react-app/assets/93829069/3e3ee78f-e682-4617-839c-197d767028eb)

Change this button color. Use the colors defined in App.sccs

**Comment by mademoiselle-chantal** [comment]
Hello @DamyanBG. Can l work on this issue?

**Comment by DamyanBG** [comment]
Yes @mademoiselle-chantal

**Comment by mademoiselle-chantal** [comment]
@DamyanBG l can see in the App.scss there are only those colors defined
<img width="695" alt="Screenshot 2024-04-05 at 17 00 57" src="https://github.com/DamyanBG/real-estate-react-app/assets/120084609/08e53975-a71c-4587-8df6-50ff0846ece0">

Am l supposed to pick out one l like and replace it with that one on the button or you choose the color you want?

**Comment by DamyanBG** [comment]
@mademoiselle-chantal You can choose whatever color you like from the list which you provided.

**Comment by mademoiselle-chantal** [comment]
> @mademoiselle-chantal You can choose whatever color you like from the list which you provided.

Ok, thank you.

**Comment by mademoiselle-chantal** [comment]
Hello @DamyanBG. I created a PR for the issue `Button color #345`.

**Comment by DamyanBG** [comment]
Actually I liked your implementation. Thank you!
