### ISSUE TITLE
Styling of text area

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#364]
![text area](https://github.com/DamyanBG/real-estate-react-app/assets/93829069/ac6a7ce2-ae10-4334-9e1e-7b8e65081734)

Add style to text area

**Comment by GeorgiosDrivas** [comment]
@DamyanBG Hello! I would like to work on this issue.

**Comment by GeorgiosDrivas** [comment]
I made some changes in the App.scss file in order to achieve the disered result. The pull request has passed all the checks and gave me the ability to merge it my self. Should I proceed and merge it, or wait for your approval?

**Comment by GeorgiosDrivas** [comment]
I created a pull request. I accidentally made a pull request in my forked repository, so please ignore that.
