### ISSUE TITLE
Handle error on image loading

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#386]
![image](https://github.com/DamyanBG/real-estate-react-app/assets/93829069/72e22fd5-a159-444a-861b-38a8ed1009cd)

If the image doesn't load, show the default home image.

**Comment by SaxenaShiv** [comment]
Hi, I am interested in this issue. Please assign this to me.

**Comment by DamyanBG** [comment]
Hello,

@SaxenaShiv , welcome to the project. I will assign the task to you when I see pull request from you.

You will find the bug in HomeCard component.

**Comment by khanSoliheen** [comment]
@DamyanBG, I have raised a pull request for this. Please review it. Thank you.

**Comment by DamyanBG** [comment]
> @DamyanBG, I have raised a pull request for this. Please review it. Thank you.

Just reviewed it and added some comments.
