### ISSUE TITLE
[Improvement] Redesigning the buttons for 'View Details'

### ISSUE THREAD

**Issue by ItsMeRaseeca** [DamyanBG/real-estate-react-app#421]
![image](https://github.com/DamyanBG/real-estate-react-app/assets/142300062/60c3e5d5-0d3c-437a-8765-a4227124495e)

Issue: There should be consistency in the 'View Details' button for the property cards. 

Fix : I will make sure that the first Property card has the same button design as the other two cards. Also, for improvement, I can add some border radius to the button.

Please assign this issue to me, thanks.

**Comment by DamyanBG** [comment]
Yes, you are right.
