### ISSUE TITLE
Rent link color

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#49]
I can see that Rent from the header is with blue color. It have to be as the others (when open this issue it is black color).

**Comment by bellhwi** [comment]
Try this code in Header.scss

```
a {
  color: inherit;
}
```

'Link' from the Header component is considered the 'a' tag after it's rendered.
You can use ‘inherit’ for the 'a' tag to use the value from its parent element(which is 'ul').
I hope this is the answer you were looking for!

**Comment by DamyanBG** [comment]
Yes
