### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#57]
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `HomePage`. See https://reactjs.org/link/warning-keys for more information.
    at article
    at HomePage (http://localhost:3000/static/js/bundle.js:856:76)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:40460:5)
    at Routes (http://localhost:3000/static/js/bundle.js:40897:5)
    at main
    at Router (http://localhost:3000/static/js/bundle.js:40835:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:39152:5)
    at div
    at App
overrideMethod @ react_devtools_backend.js:4012
printWarning @ react-jsx-dev-runtime.development.js:87
error @ react-jsx-dev-runtime.development.js:61
validateExplicitKey @ react-jsx-dev-runtime.development.js:1078
validateChildKeys @ react-jsx-dev-runtime.development.js:1105
jsxWithValidation @ react-jsx-dev-runtime.development.js:1276
HomePage @ HomePage.js:18
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19588
beginWork @ react-dom.development.js:21601
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533

**Comment by Cleyfson** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by DamyanBG** [comment]
Assigned
