### ISSUE TITLE
Sing Out and Profile

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#62]
When the user successfully Sign in into the website, he is redirected to the initial page. I want at the same time when the user is logged in the links Sign up and Sign in to be replaced with Profile and Sign Out. 

When the user clicks on Profile, redirect him to /profile.

When the user clicks on Sign Out, make a POST request to the back end on route /auth/logout, await for status 200 and delete the token from the cookies and the userId from the localstorage. 

Return Sign up and Sign in links.

**Comment by edesuccess54** [comment]
hi, @DamyanBG I would have love to take on this issue but i keep getting error trying to run the react application even after installing the node_modules. below is the error message i keep getting.
Error: Cannot find module 'webpack'

**Comment by DamyanBG** [comment]
@edesuccess54 really interesting. Till now nobody had this issue. Can you try again in new folder to clone the repo, to run npm install and to see the result? Have you updated NodeJS to the latest version? What kind of OS you are using?

**Comment by DamyanBG** [comment]
Btw there is deployment of the application on Azure cloud. I made Github Actions pipeline and if we had problems with the dependencies, I would see a problem in build.

**Comment by edesuccess54** [comment]
i have fixed it. is this how it looks on your end?
![Screen Shot 2022-12-31 at 8 36 11 AM](https://user-images.githubusercontent.com/87667603/210129247-b0169879-07d2-4014-be7e-91a8f8349b94.png)

**Comment by DamyanBG** [comment]
Yes

**Comment by DamyanBG** [comment]
@edesuccess54 I didnt understood - do you will make that or not? Because it is important.

**Comment by DamyanBG** [comment]
I will take this

**Comment by edesuccess54** [comment]
> @edesuccess54 I didn't understood - do you will make that or not? Because it is important.

can you please explain what you mean clearly?

**Comment by DamyanBG** [comment]
I made it.
