### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#63]
We need to improve our README.

**Comment by Cleyfson** [comment]
i would like work on it

**Comment by DamyanBG** [comment]
So, first you can browse some examples of README and then to make here the README by template. 

Usually I want first to introduce that I am the owner of the project and I am responsible for the architecture. After that mention that Tihomir is my buddy, who is learning and helping with the project at the same time. After that mention that there are a lot of contributors and I am grateful for that. 

Write in new place that if some of the contributors wants to be mentioned in the README to tell me.

After that write the idea of the application - first we are here to learn and practice. This is perfect project for people with not so much experience in React. Mention if somebody wants to contribute - to open the CONTRIBUTIN.md file.

After that write the description for the business idea behind the app - we are creating an Real Estate Sell and Buy application, which will be open for everyone to use. There will be buyers, sellers and admins in this app. I think it is understandable - buyers just browse and buy, sellers are uploading real estates for sell. Admins to watch what is going on.

**Comment by DamyanBG** [comment]
After that we will mention where is the difference in our app - at the first time we will make functionality buyers and sellers to be able to chat. We will make functionality buyers and sellers to schedule meetings. After that we will make functionality to make visitations - a visitations will me some kind of open time for going to see some home for selling. The idea is that some sellers can not have time to meet with each buyer and he will spend for example 3 hours on Saturday to unlock the home and show it. At this time everybody can go and see it. Thats the idea behind visitation.

**Comment by DamyanBG** [comment]
There will be section too for news related to Real Estate, there will be map of Homes for sale. Also we will implement the same thing for Land. If somebody wants to buy or sell Land - he can do the same thing. 

In the future we will implement Rent section - there the main logic for now is to give home for rent or take it for rent.

**Comment by DamyanBG** [comment]
at the end just write how to start the application - the steps:

- clone the project
- npm install
- npm start

You can add and link to the back end and to the deployed front end - https://mango-plant-0117d3e03.2.azurestaticapps.net/

**Comment by Cleyfson** [comment]
this is what i have right now, what do you think?

![Captura de tela de 2023-01-05 18-30-04](https://user-images.githubusercontent.com/83799520/210884343-4b012653-2735-4357-920e-2f8870651555.png)
![Captura de tela de 2023-01-05 18-34-24](https://user-images.githubusercontent.com/83799520/210884346-3423f7a0-c8b4-4510-97c3-f6fcd97649cb.png)

**Comment by DamyanBG** [comment]
Awesome!

**Comment by Cleyfson** [comment]
to present the details that differentiate the application, I thought of creating a checklist similar to the one below. That can be marked as the functionalities are finished.

### Project Status

- [ ] Buyers and sellers chat.
- [ ] Schedule meetings for buyers and sellers
- [ ] Schedule visits
- [x] News section
- [ ] Map of houses for sale
- [ ] Map of lands for sale
- [ ] Rent section **_(in progress)_**
- [x] Production


If you can come with a better list of features already done and that you pretend to do in the feature, i can put  it  on. Or do you think that i can follow with the list above?.

**Comment by DamyanBG** [comment]
The list is ok

**Comment by DamyanBG** [comment]
Very good work! Thank you for the effort!
