### ISSUE TITLE
Sign up as a seller

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#67]
On Sign up page which is on /signup, please, add a checkbox with label - Sign Up as a seller. If the checkbox is active, send to the back end role "seller".

**Comment by ayobamiseun** [comment]
can i contributed to this

**Comment by DamyanBG** [comment]
Assigned

**Comment by DamyanBG** [comment]
Be awair that there are few eslint errors - #87

**Comment by ayobamiseun** [comment]
Any idea why this showing
<img width="1440" alt="Screenshot 2023-01-03 at 5 44 17 PM" src="https://user-images.githubusercontent.com/66267222/210401966-66017ce2-703a-4e25-9df4-d4689c01d85d.png">

**Comment by DamyanBG** [comment]
As I mentioned in my previous comment - there are ESLint errors. If you know how to fix them, you can assign the issue where the bug is described. If not - just turn off the eslint.

**Comment by DamyanBG** [comment]
@ayobamiseun you can pull the last version, everything is fixed

**Comment by ayobamiseun** [comment]
ok thank you for that i will pull the latest update.
Sorry for this question please. I do like to know how you are going to save the new value i am about to add to the form, i know you are using Azure for the backend. Do you have a collumn for the seller role already in your list of data to be received.
I am not really familliar with azure. 
i will like if you can direct me to where i can learn more about it

**Comment by DamyanBG** [comment]
Think for Azure like just a tool for deploying stuffs. 

If you want to see what is behind the Azure, look at this repository - https://github.com/DamyanBG/real-estate-nodejs-be

This is the back end deployed on Azure. You can even clone it and connect your local React with local NodeJS.

If you have more questions - feel free to ask.

**Comment by ayobamiseun** [comment]
Thank you. 
Good Day.
so I was looking at setting the role I will love to ask you if I can just set a new state to work with, in other take the seller role input.

**Comment by DamyanBG** [comment]
You are free to make it by your style. Just to work.

**Comment by DamyanBG** [comment]
Thank you for the effort!
