### ISSUE TITLE
restyle signin page

### ISSUE THREAD

**Issue by edesuccess54** [DamyanBG/real-estate-react-app#72]

**Comment by edesuccess54** [comment]
whats anything wrong? it was closed but not merged

**Comment by DamyanBG** [comment]
Everything is merged.

**Comment by DamyanBG** [comment]
git checkout main 
git pull origin main
and check again

**Comment by edesuccess54** [comment]
@DamyanBG great, hope you like it?

**Comment by DamyanBG** [comment]
Yes, thank you
