### ISSUE TITLE
Unexpected white color in the header

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-react-app#91]
![unexpected white color](https://user-images.githubusercontent.com/93829069/210726948-7af700e6-7987-454c-80d3-041dc6c90844.PNG)

I want the header to have 1 color for background,

**Comment by rajr79529** [comment]
I have created a PR for this issue fix. https://github.com/DamyanBG/real-estate-react-app/pull/92

**Comment by DamyanBG** [comment]
Thank you!
